name: lipsick
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==1.13.0
  - torchvision==0.14.0
  - torchaudio==0.13.0
  - cudatoolkit=11.6
  - numpy
  - scipy
  - protobuf
  - pip:
    - opencv-python
    - resampy
    - python_speech_features
    - filetype==1.2.0
    - gradio==4.26.0
    - psutil
    - tqdm
    - tensorflow==2.10.0
    - tensorflow-gpu==2.10.0
    - tensorflow-intel==2.10.0
    - ./wheels/dlib-19.22.99-cp310-cp310-win_amd64.whl
